# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestGoogleMap' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'GoogleMaps'
  pod 'GooglePlaces'

  # Pods for TestGoogleMap

  target 'TestGoogleMapTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestGoogleMapUITests' do
    # Pods for testing
  end

end
